### ISSUE TITLE
Not working with langchain due to changes and migration to langchain experimental

### ISSUE THREAD

**Issue by stephanyvargas** [ur-whitelab/chemcrow-public#13]
As of today I am using langchain perfectly with other projects. Just testing chemprop minimum script 
```
from chemcrow.agents import ChemCrow

chem_model = ChemCrow(model="gpt-4-0613", temp=0.1, verbose=True)
chem_model.run("What is the molecular weight of tylenol?")
```
Get the error
```
/home/stephany/.local/lib/python3.9/site-packages/langchain/__init__.py:34: UserWarning: Importing SerpAPIWrapper from langchain root module is no longer supported. Please use langchain.utilities.SerpAPIWrapper instead.
  warnings.warn(
/home/stephany/.local/lib/python3.9/site-packages/langchain/__init__.py:34: UserWarning: Importing LLMChain from langchain root module is no longer supported. Please use langchain.chains.LLMChain instead.
  warnings.warn(
/home/stephany/.local/lib/python3.9/site-packages/langchain/__init__.py:34: UserWarning: Importing PromptTemplate from langchain root module is no longer supported. Please use langchain.prompts.PromptTemplate instead.
  warnings.warn(
Traceback (most recent call last):
  File "/home/stephany/.local/lib/python3.9/site-packages/chemcrow/agents/chemcrow.py", line 46, in __init__
    self.llm = _make_llm(model, temp, verbose, openai_api_key)
  File "/home/stephany/.local/lib/python3.9/site-packages/chemcrow/agents/chemcrow.py", line 12, in _make_llm
    llm = langchain.chat_models.ChatOpenAI(
  File "/home/stephany/.local/lib/python3.9/site-packages/langchain/load/serializable.py", line 97, in __init__
    super().__init__(**kwargs)
  File "/home/stephany/.local/lib/python3.9/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for ChatOpenAI
__root__
  Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass  `openai_api_key` as a named parameter. (type=value_error)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephany/test_query/latest/testing.py", line 3, in <module>
    chem_model = ChemCrow(model="gpt-4-0613", temp=0.1, verbose=True)
  File "/home/stephany/.local/lib/python3.9/site-packages/chemcrow/agents/chemcrow.py", line 48, in __init__
    raise ValueError('Invalid OpenAI API key')
ValueError: Invalid OpenAI API key
```

**Comment by doncamilom** [comment]
Hi there!
The messages you get regarding langchain version are simply warnings, and do not affect execution at the moment.

The error you are getting is a `ValidationError` related to your `openai_api_key`. 
 > Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass  `openai_api_key` as a named parameter. (type=value_error)

You can also pass it as an argument to ChemCrow.

```python
from chemcrow.agents import ChemCrow:

chem_model = ChemCrow(
    model="gpt-4-0613",
    temp=0.1,
    openai_api_key="sk-...",
    verbose=True
)
chem_model.run("What is the molecular weight of tylenol?")
```
Can you please try that and let me know how it works :)
