### ISSUE TITLE
RXNRetrosynthesis failing attempts

### ISSUE THREAD

**Issue by miquelduranfrigola** [ur-whitelab/chemcrow-public#38]
Hi, thanks for a truly exciting repository.

I have obtained an `RXN4CHEM_API_KEY` and I am trying to run `chemcrow` to give suggest a synthesis plan for a given molecule.

However, code fails after multiple attempts:

```
ReactionRetrosynthesis
Action Input:
CCOC(=O)c1cnc2c(C)cc(C)cc2c1Nc1ccc(OC)c(OC)c1Exception thrown when attempting to run <function RXNRetrosynthesis.predict_retrosynthesis at 0x124731ea0>, attempt 0 of 10
Exception thrown when attempting to run <function RXNRetrosynthesis.predict_retrosynthesis at 0x124731ea0>, attempt 1 of 10
Exception thrown when attempting to run <function RXNRetrosynthesis.predict_retrosynthesis at 0x124731ea0>, attempt 2 of 10
Exception thrown when attempting to run <function RXNRetrosynthesis.predict_retrosynthesis at 0x124731ea0>, attempt 3 of 10
Exception thrown when attempting to run <function RXNRetrosynthesis.predict_retrosynthesis at 0x124731ea0>, attempt 4 of 10
Exception thrown when attempting to run <function RXNRetrosynthesis.predict_retrosynthesis at 0x124731ea0>, attempt 5 of 10
Exception thrown when attempting to run <function RXNRetrosynthesis.predict_retrosynthesis at 0x124731ea0>, attempt 6 of 10
Exception thrown when attempting to run <function RXNRetrosynthesis.predict_retrosynthesis at 0x124731ea0>, attempt 7 of 10
Exception thrown when attempting to run <function RXNRetrosynthesis.predict_retrosynthesis at 0x124731ea0>, attempt 8 of 10
Exception thrown when attempting to run <function RXNRetrosynthesis.predict_retrosynthesis at 0x124731ea0>, attempt 9 of 10
Traceback (most recent call last):
 File "/Users/mduranfrigola/Documents/GitHub/ai-intro-workshop/chemcrowdev.py", line 23, in <module>
  result = mrkl.run(prompt)
 File "/Users/mduranfrigola/miniconda3/envs/chemcrow/lib/python3.10/site-packages/chemcrow/agents/chemcrow.py", line 84, in run
  outputs = self.agent_executor({"input": prompt})
 File "/Users/mduranfrigola/miniconda3/envs/chemcrow/lib/python3.10/site-packages/langchain/chains/base.py", line 282, in __call__
  raise e
 File "/Users/mduranfrigola/miniconda3/envs/chemcrow/lib/python3.10/site-packages/langchain/chains/base.py", line 276, in __call__
  self._call(inputs, run_manager=run_manager)
 File "/Users/mduranfrigola/miniconda3/envs/chemcrow/lib/python3.10/site-packages/langchain/agents/agent.py", line 1036, in _call
  next_step_output = self._take_next_step(
 File "/Users/mduranfrigola/miniconda3/envs/chemcrow/lib/python3.10/site-packages/langchain/agents/agent.py", line 891, in _take_next_step
  observation = tool.run(
 File "/Users/mduranfrigola/miniconda3/envs/chemcrow/lib/python3.10/site-packages/langchain/tools/base.py", line 351, in run
  raise e
 File "/Users/mduranfrigola/miniconda3/envs/chemcrow/lib/python3.10/site-packages/langchain/tools/base.py", line 325, in run
  else self._run(*tool_args, **tool_kwargs)
 File "/Users/mduranfrigola/miniconda3/envs/chemcrow/lib/python3.10/site-packages/chemcrow/tools/rxn4chem.py", line 147, in _run
  prediction_id = self.predict_retrosynthesis(target)
 File "/Users/mduranfrigola/miniconda3/envs/chemcrow/lib/python3.10/site-packages/chemcrow/tools/rxn4chem.py", line 75, in newfn
  return func(*args, **kwargs)
 File "/Users/mduranfrigola/miniconda3/envs/chemcrow/lib/python3.10/site-packages/chemcrow/tools/rxn4chem.py", line 170, in predict_retrosynthesis
  raise KeyError
KeyError
```

Do you know what may be going on?

Thanks so much in advance.

**Comment by SamCox822** [comment]
I think I was able to recreate this. I printed the entire response before the error is caught and tries to re-execute and it looks like this:
```
{'response': {'payload': None, 'metadata': {'uiMessages': {'errors': [{'code': None, 'message': 'User cant create retrosynthesis for current project', 'type': 'ERROR', 'description': None, 'fieldId': None, 'target': 'TOAST', 'duration': 10000}], 'infos': [], 'warnings': []}, 'extendedPagination': {}}}}
```

which looks like it might be an error with the api key/account? lmk if this helps

**Comment by doncamilom** [comment]
Hi! I could reproduce the issue. 
Apparently it's a problem with the RXN api key. For some reason for me it solved by going to the rxn4chem website and regenerating a new API key https://rxn.app.accelerate.science/rxn/account/keys

**Comment by doncamilom** [comment]
Can someone confirm if this worked?
It's really all I did and it work. Hope that helps!

**Comment by doncamilom** [comment]
I worked on a local serving of the RXN tools, see #52.
Can you try and confirm that this works for you?

**Comment by miquelduranfrigola** [comment]
Thanks all!
I will try asap and let you know asap.

**Comment by Gaspiller** [comment]
I also encountered this problem. Even if a new API is replaced, it cannot be solved. I tried the local service, but the image file was not found.

**Comment by Farhana-Keya** [comment]
I have solved this problem. At first, create a project in rxn for chemistry website, then replace your  project id with the default one in code. Then it will resolve your problem and in website you can visualize your query under your project. I think, that's helpful.
